name: pythonblack
on: [workflow_dispatch, pull_request]

jobs:
  pythonblack_job:
    runs-on: ubuntu-latest
    name: Runs python black
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: black Runner
        uses: vkoski-godaddy/black-check@master
        id: pythonblack
        with:
          path: 'scripts/'
